import {playNarration,stopNarration,pauseNarration,setNarrationVolume} from './narration.js?v=20260916-4';
import {mountAvatar} from './avatar-canvas.js?v=20260916-11';
import {standardFlow,getImmersionPhase} from './experience.js';
import {reportPanels,reportInsight} from './report-panels.js?v=20260917-2';
import {getAssessment} from './assessment-service.js';
import {assessmentAdapter,safetyCheck,recommendationEngine,overrideRecommendation} from './assessment.js';
import {getDemoRecommendation} from './recommendation-service.js?v=20260916-1';
document.head?.insertAdjacentHTML?.('beforeend','<link rel="stylesheet" href="refinement.css?v=20260914-1"><link rel="stylesheet" href="overlay-fixes.css?v=20260917-10">');
const logoImage=document.querySelector?.('header .logo img');if(logoImage){logoImage.src='assets/images/logo-transparent.png?v=1';logoImage.width=230;logoImage.height=72}
const $=s=>document.querySelector(s),app=$('#app');
const requestedSample=typeof location!=='undefined'?new URLSearchParams(location.search).get('sample'):null;
const state={page:'home',companion:null,beforeAssessment:null,afterAssessment:null,goal:'relax',instrument:'chinese',tone:'jue',selectedPlan:null,recommendedPlan:null,recommendationSampleId:/^U00[1-9]$|^U010$/.test(requestedSample||'')?requestedSample:'U002',overrideReason:'',duration:120,immersion:{phase:'C',progress:0}};
const companions={xiaoxuan:{name:'小璇',role:'苗族少女 · 乐师',image:'assets/avatar/xiaoxuan-demo-base.png',atlas:'assets/avatar/xiaoxuan-no-blink-fast-v6.png',width:380,height:627,mouth:[172,98,38,30]},xiaoxing:{name:'小星',role:'国风青年 · 乐师',image:'assets/avatar/xiaoxing-demo-base.png',atlas:'assets/avatar/xiaoxing-no-blink-fast-v6.png',width:410,height:627,mouth:[190,66,36,25]}};
const goals={relax:'减压',sleep:'助眠',focus:'专注',energy:'提振'},scenes={ocean:'晨雾海岸',forest:'森林微光',aurora:'极光原野'},music={'piano':'西洋乐器','five-tone':'中国乐器 · 五音'},tones={gong:'宫',shang:'商',jue:'角 · 木',zhi:'徵',yu:'羽'};
// Independent resource slots: replace paths when production media becomes available.
const placeholderVideo='https://developer.mozilla.org/shared-assets/videos/flower.mp4';
export const media={video:{ocean:placeholderVideo,forest:placeholderVideo,aurora:placeholderVideo},music:{piano:'assets/audio/西方轻音乐.mp3',pop:null,'five-tone':'assets/music/tone-wood.m4a','tone-gong':'assets/music/tone-earth.m4a','tone-shang':'assets/music/tone-metal.m4a','tone-jue':'assets/music/tone-wood.m4a','tone-zhi':'assets/music/tone-fire.m4a','tone-yu':'assets/music/tone-water.m4a'},voice:{C01:null,C02:null,C03:null,F01:null,F02:null}};
let tick=null,hide=null,elapsed=0,paused=false,players=[];
const scene=(kind='ocean')=>`<div class="landscape photographic-scene" data-scene="${kind}"><div class="scene-caption">一段留给自己的时间<span>${scenes[kind]}</span></div></div>`;
const body=()=>`<div class="body-scan reference-body"><div class="body-halo"></div><img src="assets/images/body-reference.png" alt="青蓝色全身人体检测示意图，用户提供的视觉参考"/><span class="body-label label-left">PHYSIOLOGICAL<br><b>生理信号</b></span><span class="body-label label-right">RESONANCE<br><b>节律感知</b></span><div class="anatomy-caption">人体结构示意 · 非实时检测影像</div></div>`;
function go(page){stopNarration();clearInterval(tick);players.forEach(p=>p.pause());players=[];state.page=page;document.body.className=['report','safe'].includes(page)?'tech':page==='immersion'?'immersive':page==='home'?'welcome':'';$('#companion').style.opacity='1';window.scrollTo(0,0);render();if(state.page===page)playNarration(page,state.companion)}
function shell(step,title,desc,content,cls=''){app.innerHTML=`<section class="page ${cls}"><div class="step">${step}</div><h2>${title}</h2><p class="lead">${desc}</p>${content}</section>`}
const btn=(a,text,cls='primary')=>`<button class="${cls}" data-action="${a}">${text}</button>`;
const goalButtons=()=>Object.entries(goals).map(([k,v])=>`<button class="chip ${state.goal===k?'selected':''}" data-goal="${k}">${v}</button>`).join('');
function render(){
 const companion=$('#companion');
 document.body.appendChild?.(companion);
 const guide=companions[state.companion]||companions.xiaoxuan;
 if(companion){companion.hidden=!state.companion;if(companion.dataset)companion.dataset.guide=state.companion||'xiaoxuan'}
 const avatar=typeof companion?.querySelector==='function'?companion.querySelector('.avatar'):null;if(avatar){avatar.src=guide.image;avatar.alt=`${guide.name}全身数字人立绘`}
 const canvas=typeof companion?.querySelector==='function'?companion.querySelector('.avatar-canvas'):null;mountAvatar(canvas,guide);
 const companionLabel=typeof companion?.querySelector==='function'?companion.querySelector('span'):null;if(companionLabel)companionLabel.textContent=`${guide.name} · 陪你慢下来`;
 const narrationSlot=$('#narration-slot');$('header').appendChild?.(narrationSlot);
 renderPage();
 if(state.page==='report'){const stai=$('.stai-report'),overview=$('.report-overview');overview?.appendChild?.(stai)}
 const destination=state.page==='report'?$('.report-analysis'):state.page==='home'?$('.home-v2'):state.page==='immersion'?$('.immersion'):null;
 destination?.appendChild?.(companion);
 if(state.page==='immersion')destination?.appendChild?.(narrationSlot);
}
function renderPage(){const p=state.page;
if(p==='home'){document.body.className='welcome';app.innerHTML=`<section class="home home-v2"><div class="hero-image" aria-hidden="true"></div><div class="hero-copy"><div class="eyebrow"><span class="micro-star">✧</span> 留一点时间，给自己</div><h1>让心绪，<br><em>慢慢靠岸。</em></h1><p>一片风景，一段音乐，一次自在的呼吸。<br>和你的数字人伙伴一起，找到适合此刻的放松方式。</p><div class="actions">${btn('intro-xuan','开启体验 · 含语音 &nbsp; ↗')}${btn('flow','探索体验 &nbsp; →','text-btn')}</div><div class="hero-note"><span></span> 不必准备好，按你的节奏就好。</div></div><div class="scene-index"><span>01 — 03</span><i></i><p>COASTAL STILLNESS<br><b>晨雾海岸</b></p></div><div class="home-bottom"><div><span>第一步</span><h3>感知此刻</h3><p>从你的身体节律开始</p></div><div><span>第二步</span><h3>与自然同频</h3><p>让风景与音乐轻轻包围你</p></div><div><span>第三步</span><h3>看见微小变化</h3><p>记录属于自己的体验余韵</p></div><div class="journey-sign">✧<small>YOUR SPACE<br>YOUR PACE</small></div></div></section>`;return}
if(p==='intro-xuan'||p==='intro-xing'){const first=p==='intro-xuan',next=first?'intro-xing':'companion-select',who=first?'小璇':'小星',src=first?'assets/video/xiaoxuan-intro.mp4':'assets/video/xiaoxing-intro.mp4';app.innerHTML=`<section class="guide-intro"><video class="guide-intro-bg" src="${src}" autoplay muted playsinline preload="auto" aria-hidden="true"></video><video class="guide-intro-main" src="${src}" autoplay playsinline preload="auto"></video><div class="guide-intro-shade"></div><div class="guide-intro-copy"><span>MEET YOUR GUIDE · ${first?'01':'02'} / 02</span><h2>认识${who}</h2><p>${first?'来自山林与花间的温柔乐师。':'循着水光而来的国风乐师。'}</p></div><button class="intro-next" data-action="${next}">${first?'认识小星':'选择陪伴者'} →</button></section>`;const video=$('.guide-intro-main');players.push(video);video.addEventListener('ended',()=>go(next),{once:true});video.play().catch(()=>{});return}
if(p==='companion-select'){app.innerHTML=`<section class="guide-select"><div class="guide-select-head"><span>YOUR COMPANION</span><h2>这段旅程，想和谁一起？</h2><p>选择一位数字人伙伴，后续引导内容保持一致。</p></div><div class="guide-choice-grid">${Object.entries(companions).map(([key,c])=>`<button class="guide-card ${state.companion===key?'selected':''}" data-companion="${key}"><div><img src="${c.image}" alt="${c.name}全身立绘"></div><span>${c.role}</span><h3>${c.name}</h3><p>${key==='xiaoxuan'?'温柔、明亮，像一阵山间清风。':'沉静、清澈，像一段水畔旋律。'}</p><b>${state.companion===key?'已选择':'选择'} ↗</b></button>`).join('')}</div><div class="guide-select-actions"><button class="primary" data-action="consent" ${state.companion?'':'disabled'}>${state.companion?`和${companions[state.companion].name}一起开始 →`:'请先选择一位伙伴'}</button></div></section>`;return}
if(p==='flow'){shell('标准体验 · 约 22 分钟','一次完整的身心旅程。','知情同意在舱外完成；以下时长为标准安排，Demo 可提前进入下一步。',`<div class="flow-timeline">${standardFlow.map(x=>`<div><span>${x.id}</span><section><h3>${x.name}</h3><p>${x.note}</p></section><small>${x.seconds?Math.floor(x.seconds/60)+':'+String(x.seconds%60).padStart(2,'0'):'不计入'}</small></div>`).join('')}</div>${btn('intro-xuan','开启体验 →')}`,'narrow');return}
if(p==='consent'){shell('S · 知情 / 监护人同意','开始之前，先安心。','这段时间属于你。我们希望你清楚了解接下来会发生什么。',`<div class="items">${[['✧','这是一段放松体验','不用于医疗诊断或治疗。'],['≈','数据用于体验反馈','本 Demo 使用模拟数据；正式版用于比较体验前后的变化。'],['↗','随时可以停下来','你可以随时退出，不需要说明理由。'],['☆','如果你未满 18 岁','需要监护人知情同意后再开始。']].map(x=>`<div class="item"><span>${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div></div>`).join('')}</div><label class="check"><input id="consent" type="checkbox">我已完成舱外知情确认；未成年时已取得监护人同意</label><div class="actions"><button class="primary" id="continue" data-action="scan" disabled>安心继续 →</button></div>`,'narrow');$('#consent').onchange=e=>$('#continue').disabled=!e.target.checked;return}
if(p==='scan'||p==='after'){const after=p==='after';shell(after?'H · 后测评估 / 标准 2 分钟':'0 · 前测评估 / 标准 2 分 30 秒',after?'欢迎回来。':'先安静地，坐一会儿。',after?'再次完成 STAI-S，记录体验后的状态。':'本次前后测统一采用 STAI-S 状态焦虑量表。',`<div class="stai-card"><span>STAI-S · STATE ANXIETY</span><h3>状态焦虑量表</h3><p>正式版共 20 项、四级作答；Demo 自动载入授权接口的示例结果。</p><div class="stai-scale"><i>几乎没有</i><b></b><b></b><b></b><b></b><i>非常明显</i></div></div><div class="import-experience compact"><p class="breath-caption">自然呼吸，不用刻意调整。</p><div class="actions">${btn('load',after?'完成后测，查看报告 →':'完成前测，进入准备 →')}</div><p id="load-status" class="import-status" role="status">演示模式 · 数据接口已预留</p></div>`,'narrow import-page');return}
if(p==='safe'){shell('安全确认','当前状态需要进一步确认','请由工作人员进行人工评估。当前检测结果无法进入正常推荐流程。',`<div class="notice">体验已暂停。人工接管接口已预留，本 Demo 不会自动解除安全拦截。</div>${btn('home','返回首页','secondary')}`,'narrow');return}
if(p==='prepare'){app.innerHTML=`<section class="standby"><div class="standby-visual">${scene('ocean')}<div class="standby-glow"></div></div><div class="standby-copy"><span>A · 接入准备</span><h2>先让视线，<br>慢慢安静下来。</h2><p>低对比暖光与极少信息，帮助你从现实环境平滑过渡。</p>${btn('select-goal','开始选择 →')}</div></section>`;return}
if(p==='recommend'){const plan=state.selectedPlan;const source=plan.sourceType==='real_extracted'?'真实前测样本':'模拟前测样本';shell('B2 · 决策确认 / 标准 1 分钟','一段与你同频的风景。','评分结果已通过 recommendation_v2 与带标签素材库完成匹配。',`<div class="plan">${scene(plan.scene)}<div><div class="eyebrow">${source} ${plan.sampleId||''} · 已通过安全检查</div><h2>${plan.title}</h2><div class="tags">${goals[plan.goal]} · ${music[plan.music]} · ${plan.functionTag||'慢节奏'}</div><p>${plan.reason}</p><div class="recommend-alternative"><span>算法推荐 · ${plan.videoId||'素材库'}</span><p>${state.recommendedPlan?.title||plan.title} · 匹配度 ${Math.round((plan.recommendationScore||0)*100)}%</p>${btn('use-recommendation','采用这个推荐','text-btn')}</div><div class="duration-choice"><span>体验时长</span>${[120,750].map(n=>`<button class="chip ${state.duration===n?'selected':''}" data-duration="${n}">${n===120?'快速演示 · 2 分钟':'标准沉浸 · 12 分 30 秒'}</button>`).join('')}</div><div class="actions">${btn('immersion','就从这里开始 ↗')}${btn('select','我想自己选','text-btn')}</div><details class="tiny"><summary>为什么推荐这个？</summary><p>${(plan.reasons||[plan.reason]).map(escapeHtml).join('；')}。推荐由评分结果、六维视频标签与安全过滤共同生成；体验后数据仍为模拟数据。</p></details></div></div>`);return}
if(p==='select'||p==='select-goal'){shell('A2 · 01 / 03','此刻，你更想要什么？','只选一个方向，之后仍可更换。',`<div class="split-choice"><div class="choice-list">${goalButtons()}</div><div class="choice-preview preview-goal goal-${state.goal}"><div class="goal-preview-shade"></div><span>GOAL</span><h3>${goals[state.goal]}</h3><p>让体验围绕此刻最需要的状态展开。</p></div></div><div class="actions">${btn('select-mode','下一步 →')}</div>`,'choice-page');return}
if(p==='select-mode'){shell('A2 · 02 / 03','选择声音的质地。','试听为十秒示意片段，正式音源可由资源接口替换。',`<div class="split-choice"><div class="choice-list"><button class="choice-tile ${state.instrument==='chinese'?'selected':''}" data-instrument="chinese"><b>中国乐器</b><span>宫 · 商 · 角 · 徵 · 羽</span></button><button class="choice-tile ${state.instrument==='western'?'selected':''}" data-instrument="western"><b>西洋乐器</b><span>柔和器乐组合</span></button></div><div class="choice-preview preview-sound sound-${state.instrument}"><span>SOUND</span><h3>${state.instrument==='chinese'?'五音疗愈':'西洋器乐'}</h3>${btn('sample','试听示例 · 10 秒','secondary')}</div></div><div class="actions">${btn('select-preference','下一步 →')}</div>`,'choice-page');return}
if(p==='select-preference'){const chinese=state.instrument==='chinese';shell('A2 · 03 / 03',chinese?'选择一种五音调式。':'选择想进入的场景。','右侧封面提供静态示例预览。',`<div class="split-choice"><div class="choice-list">${chinese?Object.entries(tones).map(([k,v])=>`<button class="choice-tile ${state.tone===k?'selected':''}" data-tone="${k}"><b>${v}</b><span>试听十秒示例</span></button>`).join(''):Object.entries(scenes).map(([k,v])=>`<button class="choice-tile ${state.selectedPlan.scene===k?'selected':''}" data-scene="${k}"><b>${v}</b><span>查看封面</span></button>`).join('')+'<button class="choice-tile disabled" disabled><b>自定义</b><span>二期开放</span></button>'}</div><div class="choice-preview scene-cover mode-${state.instrument} tone-${state.tone}" data-scene="${state.selectedPlan.scene}">${scene(state.selectedPlan.scene)}<h3>${chinese?tones[state.tone]:scenes[state.selectedPlan.scene]}</h3></div></div><div class="actions">${btn('confirm-plan','确认选择，查看推荐 →')}</div>`,'choice-page');return}
if(p==='immersion'){startImmersion();return}
if(p==='report'){renderReport();return}
if(p==='done'){shell('10 / 星续 · 下一次相遇','把这一点安稳，带回生活。','愿你离开屏幕后，也能给自己留一点呼吸的空间。',`<div class="success-mark">✧</div><p>累的时候，可以再来听听风、看看海。<br>我们不急，按你的节奏就好。</p><div class="actions">${btn('home','完成这段旅程 ↗')}${btn('report','再看看报告','text-btn')}</div>`,'narrow center')}
}
async function loadData(raw){const after=state.page==='after',a=assessmentAdapter(raw,after?'after':'before');if(!safetyCheck(a)){go('safe');return}state[after?'afterAssessment':'beforeAssessment']=a;if(!after){try{state.recommendedPlan=await getDemoRecommendation({sampleId:state.recommendationSampleId,goal:state.goal,instrument:state.instrument,tone:state.tone})}catch(err){console.warn(err);state.recommendedPlan=recommendationEngine(a,state.goal)}state.selectedPlan={...state.recommendedPlan}}go(after?'report':'prepare')}
function playVoice(key){playNarration(key,state.companion)}
function playSample(){players.forEach(p=>p.pause());players=[];const src=state.instrument==='chinese'?(media.music['tone-'+state.tone]||media.music['five-tone']):media.music.piano;if(!src)return;const audio=new Audio(src);audio.volume=.65;players.push(audio);audio.play().catch(()=>{});setTimeout(()=>{audio.pause();audio.currentTime=0},10000)}
function startImmersion(){elapsed=0;paused=false;app.innerHTML=`<div class="immersion">${scene(state.selectedPlan.scene)}<div class="soft"></div><div class="imm-hint">素材库 · ${escapeHtml(state.selectedPlan.title)} / 视频静音</div><div class="words" id="words">跟着画面，慢慢地往里走……</div><div class="imm-controls">${btn('home','退出体验','')}${btn('pause','暂停','')}<label>音量<input id="volume" type="range" min="0" max="1" value="0.5" step=".05" aria-label="音量"></label>${btn('after','进入后测 →','')}</div><div class="imm-progress"></div></div>`;
const v=state.selectedPlan.videoUrl||media.video[state.selectedPlan.scene];if(v){
 const video=document.createElement('video');video.className='imm-video';video.muted=true;video.autoplay=true;video.loop=true;video.playsInline=true;video.preload='auto';
 const container=$('.immersion'),background=$('.immersion>.landscape'),hint=$('.imm-hint');
 const fallback=()=>{video.style.opacity='0';background.style.display='';hint.textContent='DEMO · 视频暂不可用，已显示动态场景';container.classList.remove('video-ready')};
 video.addEventListener('playing',()=>{video.style.opacity='1';background.style.display='none';hint.textContent=`素材库 · ${state.selectedPlan.title} / 视频静音`;container.classList.add('video-ready')});
 video.addEventListener('error',fallback);video.src=v;container.prepend(video);players.push(video);video.play().catch(fallback);
}
const audioPath=state.instrument==='chinese'?(media.music['tone-'+state.tone]||media.music['five-tone']):media.music[state.selectedPlan.music];if(audioPath&&typeof Audio!=='undefined'){const a=new Audio(audioPath);a.loop=true;a.volume=.5;players.push(a);a.play().catch(()=>{})}$('#volume').oninput=e=>{const volume=Number(e.target.value);players.forEach(p=>p.volume=volume);setNarrationVolume(volume)};playVoice('C01');
const visible=()=>{const c=$('.imm-controls');if(c)c.style.opacity=1;clearTimeout(hide);hide=setTimeout(()=>{if(c){c.style.opacity=0}},3500)};$('.immersion').onpointermove=visible;$('.immersion').onfocusin=visible;visible();
tick=setInterval(()=>{if(paused)return;elapsed++;state.immersion.progress=elapsed/state.duration;const phase=state.duration===120?(elapsed<32?'C':elapsed<64?'D':elapsed<91?'E':elapsed<111?'F':'G'):getImmersionPhase(elapsed,state.duration).id;state.immersion.phase=phase;$('.imm-progress').style.width=`${elapsed/state.duration*100}%`;const words=$('#words');if(elapsed===10){words.textContent='什么都不用想，也不用做……';playVoice('C02')}if(elapsed===20){words.textContent='看着就好……我在这儿。';playVoice('C03')}$('#companion').style.transition='opacity 3s';$('#companion').style.opacity=phase==='C'?String(Math.max(0,1-Math.max(0,elapsed-20)/(state.duration===120?12:100))):['D','E'].includes(phase)?'0':'.8';words.style.opacity=['D','E','G'].includes(phase)?0:1;if(elapsed===(state.duration===120?91:570)){words.textContent=state.goal==='sleep'?'让这份安静，再陪你一会儿。':'慢慢地，把注意力带回身体。';playVoice('F01')}if(elapsed===(state.duration===120?101:630)&&state.goal!=='sleep'){words.textContent='感觉一下手和脚，准备好了，就轻轻睁开眼睛。';playVoice('F02')}if(elapsed===(state.duration===120?111:690)){words.style.opacity=0;players.forEach(a=>a.volume*=.3)}if(elapsed>=state.duration)go('after')},1000)
}
const escapeHtml=value=>String(value).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v===null||v===undefined?'—':String(v);
function plot(before=[],after=[]){const values=[...before,...after];if(!values.length)return '<p>暂无连续序列数据</p>';const min=Math.min(...values)-1,max=Math.max(...values)+1;const line=(a,c)=>`<polyline fill="none" stroke="${c}" stroke-width="2" points="${a.map((v,i)=>`${i/(a.length-1||1)*600},${70-(v-min)/(max-min)*60}`).join(' ')}"/>`;return `<svg class="plot" viewBox="0 0 600 85" preserveAspectRatio="none"><path d="M0 20H600M0 45H600M0 70H600" stroke="#719eb51a"/>${line(before,'#6680ae')}${line(after,'#a3dcd4')}</svg>`}
function renderReport(){const b=state.beforeAssessment,a=state.afterAssessment;if(!b||!a){go('scan');return}const insight=reportInsight(b,a),bs=b.questionnaire?.score??'—',as=a.questionnaire?.score??'—';shell('J · 本次体验报告 / 标准 2 分钟','记录这一刻的变化。','前测 → 沉浸体验 → 后测',`<div class="report-context"><span>${state.selectedPlan.title||scenes[state.selectedPlan.scene]} / ${goals[state.selectedPlan.goal]} / ${music[state.selectedPlan.music]}</span><span>后测为 DEMO 模拟数据 · 非医学结论</span></div><section class="report-dashboard"><aside class="report-overview"><div class="report-body">${body()}</div><div class="stai-report"><div><span>STAI-S · 状态焦虑</span><strong>${fmt(bs)} <i>→</i> ${fmt(as)}</strong></div><div class="stai-track"><i style="width:${Math.min(100,Number(bs)||0)}%"></i><i style="width:${Math.min(100,Number(as)||0)}%"></i></div><p>同一量表前后对照，仅记录本次状态。</p></div></aside><section class="report-data">${reportPanels(b,a)}</section><aside class="report-analysis"><span class="narrative-label">本次观察</span><h3>身体的变化，留在这一页。</h3><p>${insight.analysis}</p><div class="next-suggestion"><span class="narrative-label">下次建议</span><p>${insight.suggestion}</p></div><small>规则摘要 · 非医学诊断</small></aside></section><details class="report-method"><summary>补充参数 · 状态向量</summary><div class="vector-list">${Object.keys({...b.stateVector,...a.stateVector}).map(k=>`<div><span>${escapeHtml(k)}</span><b>${fmt(b.stateVector[k])} → ${fmt(a.stateVector[k])}</b></div>`).join('')}</div></details><div class="report-finish"><p>把这一点安稳，带回生活。</p>${btn('done','完成本次体验 ↗')}</div>`,'report');}
document.addEventListener('click',async e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.companion){state.companion=el.dataset.companion;render();return}if(el.dataset.intention){state.goal=el.dataset.intention;go('consent');return}if(el.dataset.goal){state.goal=el.dataset.goal;if(state.selectedPlan)state.selectedPlan=overrideRecommendation(state.selectedPlan,{goal:state.goal});render();return}if(el.dataset.instrument){state.instrument=el.dataset.instrument;state.selectedPlan=overrideRecommendation(state.selectedPlan,{instrument:state.instrument,music:state.instrument==='chinese'?'five-tone':'piano'});render();return}if(el.dataset.tone){state.tone=el.dataset.tone;state.selectedPlan=overrideRecommendation(state.selectedPlan,{tone:state.tone});render();return}if(el.dataset.scene){state.selectedPlan=overrideRecommendation(state.selectedPlan,{scene:el.dataset.scene,title:scenes[el.dataset.scene]});render();return}if(el.dataset.music){state.selectedPlan=overrideRecommendation(state.selectedPlan,{music:el.dataset.music});render();return}if(el.dataset.duration){state.duration=Number(el.dataset.duration);render();return}const a=el.dataset.action;if(!a)return;if(a==='sample'){playSample();el.textContent='正在试听 · 10 秒';el.disabled=true;setTimeout(()=>{el.textContent='试听示例 · 10 秒';el.disabled=false},10000);return}if(a==='load'){el.disabled=true;const page=state.page;try{const raw=await getAssessment(page==='after'?'after':'before');if(state.page===page)await loadData(raw)}catch(err){if(state.page===page){$('#load-status').textContent=err.message;el.disabled=false}}return}if(a==='confirm-plan'){if(!safetyCheck(state.beforeAssessment)){go('safe');return}try{state.recommendedPlan=await getDemoRecommendation({sampleId:state.recommendationSampleId,goal:state.goal,instrument:state.instrument,tone:state.tone});state.selectedPlan={...state.recommendedPlan}}catch(err){console.warn(err);state.recommendedPlan=recommendationEngine(state.beforeAssessment,state.goal,{instrument:state.instrument,tone:state.tone});state.selectedPlan={...state.recommendedPlan}}go('recommend');return}if(a==='use-recommendation'){if(!safetyCheck(state.beforeAssessment)){go('safe');return}state.selectedPlan={...state.recommendedPlan};go('recommend');return}if(a==='immersion'&&!safetyCheck(state.beforeAssessment)){go('safe');return}if(a==='pause'){paused=!paused;pauseNarration(paused);el.textContent=paused?'继续':'暂停';players.forEach(p=>paused?p.pause():p.play().catch(()=>{}));return}if(a==='home'){state.companion=null;state.beforeAssessment=null;state.afterAssessment=null;state.selectedPlan=null;state.recommendedPlan=null}go(a)});
$('#home').onclick=e=>{e.preventDefault();go('home')};render();
// Explicit, demo-only report preview; never reads a user's server assessment.
if(typeof location!=='undefined'&&new URLSearchParams(location.search).get('preview')==='report'){
 Promise.all([getAssessment('before'),getAssessment('after')]).then(async ([before,after])=>{
  state.beforeAssessment=assessmentAdapter(before,'before');state.afterAssessment=assessmentAdapter(after,'after');
  if(!safetyCheck(state.beforeAssessment)||!safetyCheck(state.afterAssessment)){go('safe');return}
  try{state.selectedPlan=await getDemoRecommendation({sampleId:state.recommendationSampleId,goal:'relax'});state.recommendedPlan={...state.selectedPlan}}catch{state.selectedPlan=recommendationEngine(state.beforeAssessment,'relax')}go('report');
 }).catch(()=>{go('home')});
}
