import {playNarration,stopNarration,pauseNarration,setNarrationVolume} from './narration.js';
import {standardFlow,getImmersionPhase} from './experience.js';
import {reportPanels,reportInsight} from './report-panels.js';
import {getAssessment} from './assessment-service.js';
import {assessmentAdapter,safetyCheck,recommendationEngine,overrideRecommendation} from './assessment.js';
const $=s=>document.querySelector(s),app=$('#app');
const state={page:'home',beforeAssessment:null,afterAssessment:null,goal:'relax',selectedPlan:null,recommendedPlan:null,overrideReason:'',duration:120,immersion:{phase:'C',progress:0}};
const goals={relax:'放松一点',sleep:'好好休息',focus:'找回专注',energy:'多一点能量',release:'舒展心绪'},scenes={ocean:'晨雾海岸',forest:'林间微光',aurora:'极光来信'},music={'piano':'钢琴曲','pop':'流行音乐','five-tone':'五音疗愈'};
// Independent resource slots: replace paths when production media becomes available.
const placeholderVideo='https://developer.mozilla.org/shared-assets/videos/flower.mp4';
export const media={video:{ocean:placeholderVideo,forest:placeholderVideo,aurora:placeholderVideo},music:{piano:null,pop:null,'five-tone':null},voice:{C01:null,C02:null,C03:null,F01:null,F02:null}};
let tick=null,hide=null,elapsed=0,paused=false,players=[];
const scene=(kind='ocean')=>`<div class="landscape photographic-scene" data-scene="${kind}"><div class="scene-caption">一段留给自己的时间<span>${scenes[kind]}</span></div></div>`;
const body=()=>`<div class="body-scan reference-body"><div class="body-halo"></div><img src="assets/images/body-reference.png" alt="青蓝色全身人体检测示意图，用户提供的视觉参考"/><span class="body-label label-left">PHYSIOLOGICAL<br><b>生理信号</b></span><span class="body-label label-right">RESONANCE<br><b>节律感知</b></span><div class="anatomy-caption">人体结构示意 · 非实时检测影像</div></div>`;
function go(page){stopNarration();clearInterval(tick);players.forEach(p=>p.pause());players=[];state.page=page;document.body.className=['report','safe'].includes(page)?'tech':page==='immersion'?'immersive':page==='home'?'welcome':'';$('#companion').style.opacity='1';window.scrollTo(0,0);render();if(state.page===page)playNarration(page)}
function shell(step,title,desc,content,cls=''){app.innerHTML=`<section class="page ${cls}"><div class="step">${step}</div><h2>${title}</h2><p class="lead">${desc}</p>${content}</section>`}
const btn=(a,text,cls='primary')=>`<button class="${cls}" data-action="${a}">${text}</button>`;
const goalButtons=()=>Object.entries(goals).map(([k,v])=>`<button class="chip ${state.goal===k?'selected':''}" data-goal="${k}">${v}</button>`).join('');
function render(){
 const companion=$('#companion');
 document.body.appendChild?.(companion);
 const narrationSlot=$('#narration-slot');$('header').appendChild?.(narrationSlot);
 renderPage();
 const destination=state.page==='report'?$('.eeg-grid'):state.page==='home'?$('.home-v2'):state.page==='immersion'?$('.immersion'):null;
 destination?.appendChild?.(companion);
 if(state.page==='immersion')destination?.appendChild?.(narrationSlot);
}
function renderPage(){const p=state.page;
if(p==='home'){document.body.className='welcome';app.innerHTML=`<section class="home home-v2"><div class="hero-image" aria-hidden="true"></div><div class="hero-copy"><div class="eyebrow"><span class="micro-star">✧</span> 留一点时间，给自己</div><h1>让心绪，<br><em>慢慢靠岸。</em></h1><p>一片风景，一段音乐，一次自在的呼吸。<br>和星璇一起，找到适合此刻的放松方式。</p><div class="actions">${btn('consent','开启体验 · 含语音 &nbsp; ↗')}${btn('flow','探索体验 &nbsp; →','text-btn')}</div><div class="hero-note"><span></span> 不必准备好，按你的节奏就好。</div></div><div class="scene-index"><span>01 — 03</span><i></i><p>COASTAL STILLNESS<br><b>晨雾海岸</b></p></div><div class="home-bottom"><div><span>第一步</span><h3>感知此刻</h3><p>从你的身体节律开始</p></div><div><span>第二步</span><h3>与自然同频</h3><p>让风景与音乐轻轻包围你</p></div><div><span>第三步</span><h3>看见微小变化</h3><p>记录属于自己的体验余韵</p></div><div class="journey-sign">✧<small>YOUR SPACE<br>YOUR PACE</small></div></div></section>`;return}
if(p==='flow'){shell('标准体验 · 约 22 分钟','一次完整的身心旅程。','知情同意在舱外完成；以下时长为标准安排，Demo 可提前进入下一步。',`<div class="flow-timeline">${standardFlow.map(x=>`<div><span>${x.id}</span><section><h3>${x.name}</h3><p>${x.note}</p></section><small>${x.seconds?Math.floor(x.seconds/60)+':'+String(x.seconds%60).padStart(2,'0'):'不计入'}</small></div>`).join('')}</div>${btn('consent','开启体验 →')}`,'narrow');return}
if(p==='consent'){shell('S · 知情 / 监护人同意','开始之前，先安心。','这段时间属于你。我们希望你清楚了解接下来会发生什么。',`<div class="items">${[['✧','这是一段放松体验','不用于医疗诊断或治疗。'],['≈','数据用于体验反馈','本 Demo 使用模拟数据；正式版用于比较体验前后的变化。'],['↗','随时可以停下来','你可以随时退出，不需要说明理由。'],['☆','如果你未满 18 岁','需要监护人知情同意后再开始。']].map(x=>`<div class="item"><span>${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div></div>`).join('')}</div><label class="check"><input id="consent" type="checkbox">我已完成舱外知情确认；未成年时已取得监护人同意</label><div class="actions"><button class="primary" id="continue" data-action="scan" disabled>安心继续 →</button></div>`,'narrow');$('#consent').onchange=e=>$('#continue').disabled=!e.target.checked;return}
if(p==='scan'||p==='after'){const after=p==='after';shell(after?'H · 后测评估 / 标准 2 分钟':'0 · 前测评估 / 标准 2 分 30 秒',after?'欢迎回来。':'先安静地，坐一会儿。',after?'让我们记录体验后的节律，再看看前后的变化。':'记录体验前的状态，再选择喜欢的体验。Demo 无需填写量表或准备检测文件。',`<div class="import-experience"><div class="breath-orb" aria-hidden="true"><i></i><i></i><span>✧</span></div><p class="breath-caption">自然呼吸，不用刻意调整。</p><div class="actions">${btn('load',after?'完成后测，查看报告 →':'完成前测，进入准备 →')}</div><p id="load-status" class="import-status" role="status">演示模式 · 自动使用内置示例数据</p></div>`,'narrow import-page');return}
if(p==='safe'){shell('安全确认','当前状态需要进一步确认','请由工作人员进行人工评估。当前检测结果无法进入正常推荐流程。',`<div class="notice">体验已暂停。人工接管接口已预留，本 Demo 不会自动解除安全拦截。</div>${btn('home','返回首页','secondary')}`,'narrow');return}
if(p==='prepare'){shell('A · 接入准备 / 标准 2 分钟，含模式选择','先让自己，坐得舒服。','星璇会陪你完成准备。此版为屏幕演示，无需实际佩戴设备。',`<div class="preparation-list"><div><b>01</b><h3>找到舒适的坐姿</h3><p>让双脚自然落地，肩膀轻轻放松。</p></div><div><b>02</b><h3>调整设备与音量</h3><p>正式体验由工作人员确认 VR 与手环信号。</p></div><div><b>03</b><h3>自然地呼吸</h3><p>不用追赶任何节奏，按自己的感觉来。</p></div></div><div class="actions">${btn('select','准备好了，选择体验 →')}</div>`,'narrow');return}
if(p==='recommend'){const plan=state.selectedPlan;shell('B2 · 决策确认 / 标准 1 分钟','一段与你同频的风景。','星璇为你准备了这段体验，你也可以跟随自己的喜好。',`<div class="plan">${scene(plan.scene)}<div><div class="eyebrow">你的选择 · 已通过安全检查</div><h2>${plan.title}</h2><div class="tags">${goals[plan.goal]} · ${music[plan.music]} · 慢节奏</div><p>${plan.reason}</p><div class="recommend-alternative"><span>规则推荐</span><p>${state.recommendedPlan?.title||plan.title} · ${music[state.recommendedPlan?.music||plan.music]}</p>${btn('use-recommendation','采用这个推荐','text-btn')}</div><div class="duration-choice"><span>体验时长</span>${[120,750].map(n=>`<button class="chip ${state.duration===n?'selected':''}" data-duration="${n}">${n===120?'快速演示 · 2 分钟':'标准沉浸 · 12 分 30 秒'}</button>`).join('')}</div><div class="actions">${btn('immersion','就从这里开始 ↗')}${btn('select','我想自己选','text-btn')}</div><details class="tiny"><summary>为什么推荐这个？</summary><p>规则先检查安全字段，再结合目标与疲劳标记。用户选择不会被推荐自动覆盖。此处为 Demo，不是真实 AI 分析。</p></details></div></div>`);return}
if(p==='select'){shell('A2 · 模式选择 / 并入接入准备','喜欢的，就是好的开始。','让目标、风景和声音，贴近此刻的你。',`<div class="selection-group"><h3>01 想要的感受</h3><div class="choices">${goalButtons()}</div></div><div class="selection-group"><h3>02 想去的地方</h3><div class="scene-options">${Object.entries(scenes).map(([k,v])=>`<button class="scene-option ${state.selectedPlan.scene===k?'selected':''}" data-scene="${k}">${scene(k)}${v}</button>`).join('')}</div></div><div class="selection-group"><h3>03 陪伴的声音</h3><div class="choices">${Object.entries(music).map(([k,v])=>`<button class="chip ${state.selectedPlan.music===k?'selected':''}" data-music="${k}">${v}</button>`).join('')}</div><div class="tiny">五音是可选的文化特色体验。当前各模式共用占位视频，独立音乐尚未接入。</div></div><div class="actions">${btn('confirm-plan','确认选择，看看推荐 →')}</div>`);return}
if(p==='immersion'){startImmersion();return}
if(p==='report'){renderReport();return}
if(p==='done'){shell('10 / 星续 · 下一次相遇','把这一点安稳，带回生活。','愿你离开屏幕后，也能给自己留一点呼吸的空间。',`<div class="success-mark">✧</div><p>累的时候，可以再来听听风、看看海。<br>我们不急，按你的节奏就好。</p><div class="actions">${btn('home','完成这段旅程 ↗')}${btn('report','再看看报告','text-btn')}</div>`,'narrow center')}
}
function loadData(raw){const after=state.page==='after',a=assessmentAdapter(raw,after?'after':'before');if(!safetyCheck(a)){go('safe');return}state[after?'afterAssessment':'beforeAssessment']=a;if(!after){state.recommendedPlan=recommendationEngine(a,state.goal);state.selectedPlan={...state.recommendedPlan}}go(after?'report':'prepare')}
function playVoice(key){playNarration(key)}
function startImmersion(){elapsed=0;paused=false;app.innerHTML=`<div class="immersion">${scene(state.selectedPlan.scene)}<div class="soft"></div><div class="imm-hint">DEMO · 花朵自然短片占位 / 视频静音</div><div class="words" id="words">跟着画面，慢慢地往里走……</div><div class="imm-controls">${btn('home','退出体验','')}${btn('pause','暂停','')}<label>音量<input id="volume" type="range" min="0" max="1" value="0.5" step=".05" aria-label="音量"></label>${btn('after','进入后测 →','')}</div><div class="imm-progress"></div></div>`;
const v=media.video[state.selectedPlan.scene];if(v){
 const video=document.createElement('video');video.className='imm-video';video.muted=true;video.autoplay=true;video.loop=true;video.playsInline=true;video.preload='auto';
 const container=$('.immersion'),background=$('.immersion>.landscape'),hint=$('.imm-hint');
 const fallback=()=>{video.style.opacity='0';background.style.display='';hint.textContent='DEMO · 视频暂不可用，已显示动态场景';container.classList.remove('video-ready')};
 video.addEventListener('playing',()=>{video.style.opacity='1';background.style.display='none';hint.textContent='DEMO · 花朵自然短片占位 / 视频静音';container.classList.add('video-ready')});
 video.addEventListener('error',fallback);video.src=v;container.prepend(video);players.push(video);video.play().catch(fallback);
}
const audioPath=media.music[state.selectedPlan.music];if(audioPath){const a=new Audio(audioPath);a.loop=true;a.volume=.5;players.push(a);a.play().catch(()=>{})}$('#volume').oninput=e=>{const volume=Number(e.target.value);players.forEach(p=>p.volume=volume);setNarrationVolume(volume)};playVoice('C01');
const visible=()=>{const c=$('.imm-controls');if(c)c.style.opacity=1;clearTimeout(hide);hide=setTimeout(()=>{if(c){c.style.opacity=0}},3500)};$('.immersion').onpointermove=visible;$('.immersion').onfocusin=visible;visible();
tick=setInterval(()=>{if(paused)return;elapsed++;state.immersion.progress=elapsed/state.duration;const phase=state.duration===120?(elapsed<32?'C':elapsed<64?'D':elapsed<91?'E':elapsed<111?'F':'G'):getImmersionPhase(elapsed,state.duration).id;state.immersion.phase=phase;$('.imm-progress').style.width=`${elapsed/state.duration*100}%`;const words=$('#words');if(elapsed===10){words.textContent='什么都不用想，也不用做……';playVoice('C02')}if(elapsed===20){words.textContent='看着就好……我在这儿。';playVoice('C03')}$('#companion').style.transition='opacity 3s';$('#companion').style.opacity=phase==='C'?String(Math.max(0,1-Math.max(0,elapsed-20)/(state.duration===120?12:100))):['D','E'].includes(phase)?'0':'.8';words.style.opacity=['D','E','G'].includes(phase)?0:1;if(elapsed===(state.duration===120?91:570)){words.textContent=state.goal==='sleep'?'让这份安静，再陪你一会儿。':'慢慢地，把注意力带回身体。';playVoice('F01')}if(elapsed===(state.duration===120?101:630)&&state.goal!=='sleep'){words.textContent='感觉一下手和脚，准备好了，就轻轻睁开眼睛。';playVoice('F02')}if(elapsed===(state.duration===120?111:690)){words.style.opacity=0;players.forEach(a=>a.volume*=.3)}if(elapsed>=state.duration)go('after')},1000)
}
const escapeHtml=value=>String(value).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v===null||v===undefined?'—':String(v);
function plot(before=[],after=[]){const values=[...before,...after];if(!values.length)return '<p>暂无连续序列数据</p>';const min=Math.min(...values)-1,max=Math.max(...values)+1;const line=(a,c)=>`<polyline fill="none" stroke="${c}" stroke-width="2" points="${a.map((v,i)=>`${i/(a.length-1||1)*600},${70-(v-min)/(max-min)*60}`).join(' ')}"/>`;return `<svg class="plot" viewBox="0 0 600 85" preserveAspectRatio="none"><path d="M0 20H600M0 45H600M0 70H600" stroke="#719eb51a"/>${line(before,'#6680ae')}${line(after,'#a3dcd4')}</svg>`}
function renderReport(){const b=state.beforeAssessment,a=state.afterAssessment;if(!b||!a){go('scan');return}const insight=reportInsight(b,a);shell('J · 本次体验报告 / 标准 2 分钟','记录这一刻的变化。','前测 → 沉浸体验 → 后测',`<div class="report-context"><span>${scenes[state.selectedPlan.scene]} / ${goals[state.selectedPlan.goal]} / ${music[state.selectedPlan.music]}</span><span>DEMO 模拟数据 · 非医学结论</span></div><section class="report-overview"><div class="report-body">${body()}</div><div class="report-narrative"><div><span class="narrative-label">本次观察</span><h3>身体的变化，留在这一页。</h3><p>${insight.analysis}</p></div><div class="next-suggestion"><span class="narrative-label">下次建议</span><p>${insight.suggestion}</p></div><small>星璇 · 规则摘要，未接入真实 AI 分析</small></div></section>${reportPanels(b,a)}<details class="report-method"><summary>补充参数 · 状态向量</summary><div class="vector-list">${Object.keys({...b.stateVector,...a.stateVector}).map(k=>`<div><span>${escapeHtml(k)}</span><b>${fmt(b.stateVector[k])} → ${fmt(a.stateVector[k])}</b></div>`).join('')}</div></details><div class="report-finish"><p>把这一点安稳，带回生活。</p>${btn('done','完成本次体验 ↗')}</div>`,'report');}
document.addEventListener('click',async e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.intention){state.goal=el.dataset.intention;go('consent');return}if(el.dataset.goal){state.goal=el.dataset.goal;if(state.selectedPlan)state.selectedPlan=overrideRecommendation(state.selectedPlan,{goal:state.goal});render();return}if(el.dataset.scene){state.selectedPlan=overrideRecommendation(state.selectedPlan,{scene:el.dataset.scene,title:scenes[el.dataset.scene]});render();return}if(el.dataset.music){state.selectedPlan=overrideRecommendation(state.selectedPlan,{music:el.dataset.music});render();return}if(el.dataset.duration){state.duration=Number(el.dataset.duration);render();return}const a=el.dataset.action;if(!a)return;if(a==='load'){el.disabled=true;const page=state.page;try{const raw=await getAssessment(page==='after'?'after':'before');if(state.page===page)loadData(raw)}catch(err){if(state.page===page){$('#load-status').textContent=err.message;el.disabled=false}}return}if(a==='confirm-plan'){if(!safetyCheck(state.beforeAssessment)){go('safe');return}state.recommendedPlan=recommendationEngine(state.beforeAssessment,state.goal);state.selectedPlan={...state.selectedPlan,goal:state.goal,title:scenes[state.selectedPlan.scene],reason:'这段体验保留了你选择的目标、场景和音乐风格。你可以继续，也可以参考下面的推荐。'};go('recommend');return}if(a==='use-recommendation'){if(!safetyCheck(state.beforeAssessment)){go('safe');return}state.selectedPlan={...state.recommendedPlan};go('recommend');return}if(a==='immersion'&&!safetyCheck(state.beforeAssessment)){go('safe');return}if(a==='pause'){paused=!paused;pauseNarration(paused);el.textContent=paused?'继续':'暂停';players.forEach(p=>paused?p.pause():p.play().catch(()=>{}));return}if(a==='home'){state.beforeAssessment=null;state.afterAssessment=null;state.selectedPlan=null;state.recommendedPlan=null}go(a)});
$('#home').onclick=e=>{e.preventDefault();go('home')};render();
// Explicit, demo-only report preview; never reads a user's server assessment.
if(typeof location!=='undefined'&&new URLSearchParams(location.search).get('preview')==='report'){
 Promise.all([getAssessment('before'),getAssessment('after')]).then(([before,after])=>{
  state.beforeAssessment=assessmentAdapter(before,'before');state.afterAssessment=assessmentAdapter(after,'after');
  if(!safetyCheck(state.beforeAssessment)||!safetyCheck(state.afterAssessment)){go('safe');return}
  state.selectedPlan=recommendationEngine(state.beforeAssessment,'relax');go('report');
 }).catch(()=>{go('home')});
}


